Traceback (most recent call last):
  File "/sc-projects/sc-proj-dh-ukb-intergenics/envs/networkvi_py310/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sc-projects/sc-proj-dh-ukb-intergenics/envs/networkvi_py310/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/sc-projects/sc-proj-dh-ukb-intergenics/envs/networkvi_py310/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/sc-projects/sc-proj-dh-ukb-intergenics/envs/networkvi_py310/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/sc-projects/sc-proj-dh-ukb-intergenics/envs/networkvi_py310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/sc-projects/sc-proj-dh-ukb-intergenics/envs/networkvi_py310/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/sc-projects/sc-proj-dh-ukb-intergenics/envs/networkvi_py310/lib/python3.10/site-packages/nbclient/client.py", line 1005, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/sc-projects/sc-proj-dh-ukb-intergenics/envs/networkvi_py310/lib/python3.10/site-packages/nbclient/client.py", line 806, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/sc-projects/sc-proj-dh-ukb-intergenics/envs/networkvi_py310/lib/python3.10/site-packages/nbclient/client.py", line 856, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['vae =NETWORKVI(', '    adata,', '    n_genes=len(adata.var[adata.var["modality"] == "Gene Expression"]),', '    n_proteins=adata.obsm["protein_expression"].shape[1],', '    ensembl_ids_genes=np.array(adata.var[adata.var["modality"] == "Gene Expression"]["gene_stable_id"]),']
...
['    standard_gene_size=5,', '    standard_go_size=2,', ')', '', 'vae.train(max_epochs=10, adversarial_mixing=False, save_best=False)']
-------------------

